server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Andrzej
    url: jdbc:postgresql://localhost:5432/invoicer
    username: postgres
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

ocr:
  data-path: /resources/static/pol.traindeddata

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000